### ISSUE TITLE
Can't connect to secured networks

### ISSUE THREAD

**Issue by sheyning** [OCD0711/MacOS-XPS-9700-OpenCore#6]
I can only connect to an open network, if I try connecting to my secured hotspot and type in my password it doesn't connect and if I click on on again it doesn't even ask for a password and nothing happens.

**Comment by sheyning** [comment]
Same goes for Bluetooth, can't connect anything but it discovers devices.

**Comment by sheyning** [comment]
Ok found out that the wifi problem seems to be a problem with windows hotspot(?) And bluetooth probably can't connect to low energy devices like my mx master 3 since it seems to work with some other devices. Also wireless speeds are rather slow (20mbps~) but that's probably not something you can fix.

**Comment by ocd0711** [comment]
It takes a while for the network card to work normally after booting
